[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "ray-tabular-regression"
version = "1.0.0"
requires-python = ">=3.11"
dependencies = ["boto3==1.40.0", "cryptography==45.0.6", "mlflow-skinny==3.14.0", "numpy==1.26.4", "PyYAML==6.0.2", "ray==2.48.0"]

[tool.setuptools.packages.find]
where = ["src"]
